=== mfulton26/adventofcode/testCases.schema.json
{
  "description": "The definition of zero or more test cases.",
  "$id": "https://mfulton26.github.io/adventofcode/testCases.schema.json",
  "$schema": "http://json-schema.org/schema#",
  "type": "array",
  "items": {
    "description": "The definition of a single test case.",
    "type": "object",
    "properties": {
      "name": {
        "description": "The name of the test case to be used in reporting, etc.",
        "type": "string"
      },
      "functionName": {
        "description": "The name of the target function to invoke in testing. Defaults to `solve`.",
        "type": "string",
        "default": "solve"
      },
      "input": {
        "description": "The first argument to pass to the target function. Must be a string or an array of strings to represent a multline string. Can be used with `options` but not with `args`.",
        "type": ["string", "array"],
        "items": { "type": "string" }
      },
      "options": {
        "description": "The second argument to pass to the target function. Typically an object."
      },
      "args": {
        "description": "An entire array of arguments to pass to the target function. Cannot be used with `input` or `options`. Using `input` is more convenient but `args` gives more control when needed.",
        "type": "array"
      },
      "expected": {
        "description": "The expected result returned from the target function. Typically a string or number."
      }
    },
    "required": ["expected"],
    "if": { "required": ["input"] },
    "then": { "not": { "required": ["args"] } },
    "else": { "required": ["args"], "not": { "required": ["options"] } }
  }
}

=== mfulton26/adventofcode/year2015/day10/part1/testCases.json
[
  {
    "functionName": "lookAndSay",
    "input": "1",
    "options": { "times": 1 },
    "expected": "11"
  },
  {
    "functionName": "lookAndSay",
    "input": "11",
    "options": { "times": 1 },
    "expected": "21"
  },
  {
    "functionName": "lookAndSay",
    "input": "21",
    "options": { "times": 1 },
    "expected": "1211"
  },
  {
    "functionName": "lookAndSay",
    "input": "1211",
    "options": { "times": 1 },
    "expected": "111221"
  },
  {
    "functionName": "lookAndSay",
    "input": "111221",
    "options": { "times": 1 },
    "expected": "312211"
  }
]

=== mfulton26/adventofcode/year=2015/day=7/part=1/testCases.json
[
  {
    "name": "example",
    "functionName": "solveAll",
    "input": [
      "123 -> x",
      "456 -> y",
      "x AND y -> d",
      "x OR y -> e",
      "x LSHIFT 2 -> f",
      "y RSHIFT 2 -> g",
      "NOT x -> h",
      "NOT y -> i"
    ],
    "expected": {
      "d": 72,
      "e": 507,
      "f": 492,
      "g": 114,
      "h": 65412,
      "i": 65079,
      "x": 123,
      "y": 456
    }
  }
]
